---
title: "DV Assignment-2"
author: "Akhil Gaur"
date: "10 February 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(flexdashboard)
library(tm)
library(SnowballC)
library(wordcloud)
library(stringr)
library(RColorBrewer)
library(dplyr)
library(wordcloud)
library(reshape2)
library(plotly)
tweets <- read.csv("C:/Users/Admin/Desktop/narendramodi_tweets (2).csv")

```

## Total Number of Tweets


```{r}
total_tweets = nrow(tweets)
valueBox(total_tweets,icon = 'fa-pencil',color = 'red')
```

### 	Average number of retweets

```{r}
avg_retweets = round(sum(tweets$retweets_count)/nrow(tweets))

valueBox(avg_retweets,icon = "fa-pencil",color = 'green')
```
### 	Average number of favourites

```{r}
avg_fav <- round(sum(tweets$retweets_count)/nrow(tweets))
valueBox(avg_fav,icon = "fa-pencil",color = 'blue')

```

row {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
tweets$date <- as.Date(tweets$created_at,'%Y-%m-%d  %H:%M:%S')
tweets$year <- format(tweets$date,'%Y')
tweets$month <- format(tweets$date,'%m')
tweets$year_month <- format(tweets$date,'%Y-%m')
tweets2016 <- subset(tweets,year=='2016')
tweets2016$quarter <- quarters(as.Date(tweets2016$created_at))
#head(tweets2016)
#tweets2016Q1 <- subset(tweets2016,quarter=='Q1')
tweets2016$text <- as.character(tweets2016$text)

word_list <- strsplit(tweets2016$text,' ')
words <- unlist(word_list)
words_count <- table(words)
words_count <-sort(words_count,decreasing = T)
words_count <- as.data.frame(words_count)
top_words <- head(words_count,50)
stop_words <- stopwords()
custom_stop_words <- c('&amp;','RT','I','My','The','will','We','This','us','will','can')

words_count <- words_count[!words_count$words %in% stop_words,]
words_count <- words_count[!words_count$words %in% custom_stop_words,]
#head(words_count,50)
top_words2016 <- c("india","people","pm","president","wishes")

for (word in top_words2016){
  tweets2016[word] <- str_count(tweets2016$text,word)
}

#head(tweets)
tweets1 <- tweets2016  %>% group_by(quarter) %>% summarise(India= sum(india,na.rm=T),People= sum(people,na.rm=T),PM=sum(pm,na.rm=T),President = sum(president,na.rm=T),Wishes=sum(wishes,na.rm=T)) 
#tweets1
tweets2 <- melt(tweets1,id.vars= "quarter")
names(tweets2)<- c("Quarter","Top_Words","Count")
ggplot(tweets2,aes(Quarter,Count)) + geom_bar(fill="orange",stat ="identity") +facet_wrap(~Top_Words)


```
row {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}
hashtag_tweets = subset(tweets2016,select = c(5,10,18)) 
hashtag_tweets = subset(hashtag_tweets,hashtag_tweets$hashtags_count>0)
hashtag_words_list <- str_extract_all(hashtag_tweets$text,"#\\S+")
hashtag_wordunlist <- unlist(hashtag_words_list)
hashtag_words <- table(hashtag_wordunlist)
hashtag_words <- sort(hashtag_words,decreasing = T)
hashtag_count <- as.data.frame(hashtag_words)
top_hashtag_words <- head(hashtag_count,5)
top_hashtag_words <- c('#TirangaYatra','#Sandesh2Soldiers','#MannKiBaat','#YogaDay','#TransformingIndia')


for (word in top_hashtag_words){
hashtag_tweets[word] <- str_count(hashtag_tweets$text,word)
}

#head(select(hashtag_tweets, `#TirangaYatra`))

data_subset <- subset(hashtag_tweets,select = c(3,4,5,6,7,8)) 

a = melt(data_subset,id.vars = c("year_month"))

#head(a,25)
#names(a)
b= a %>% group_by(year_month,variable) %>% summarise(count= sum(value))
#head(b)
g<- ggplot(b,aes(x=year_month,y=count,group=variable,color=variable)) +geom_line()
ggplotly(g)

```
### Chart C

```{r}

hashtag_wordcloud <- head(hashtag_words,30)
hashtag_wordcloud <- as.data.frame(hashtag_wordcloud)
wordcloud(hashtag_wordcloud$hashtag_wordunlist,hashtag_wordcloud$Freq,scale = c(2,0.4),colors = brewer.pal(6,'Dark2'))

```